os:
  - linux
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
git:
  depth: 3
env:
  - FLUTTER_VERSION=stable
  - FLUTTER_VERSION=dev
matrix:
  allow_failures:
    - env: FLUTTER_VERSION=dev
before_script:
  - mkdir voxxedapp
  - mv *!(voxxedapp|.travis.yml|travis_script.sh) voxxedapp
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
  - chmod +x travis_script.sh
script:
  - ./travis_script.sh
cache:
  directories:
    - $HOME/shared/.pub-cache
notifications:
  email:
    brogdon+github@gmail.com
