name: voxxedapp
description: Displays details about upcoming Voxxed Days

environment:
  sdk: ^2.0.0

dependencies:
  flutter:
    sdk: flutter

  built_collection: '>=2.0.0 <4.0.0'
  built_value: ^6.1.2
  cached_network_image: ^0.4.1
  logging: ^0.11.3+1
  flutter_local_notifications: ^0.3.8
  path_provider: ^0.4.1
  rebloc: ^0.0.7
  url_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: '>=0.9.0 <0.11.0'
  built_value_generator: ^6.1.2
  flutter_launcher_icons: "^0.6.1"

flutter:
  uses-material-design: true

  assets:
    - assets/json/cold_boot.json

  fonts:
  - family: Lato
    fonts:
    - asset: assets/font/Lato-Regular.ttf
    - asset: assets/font/Lato-Italic.ttf
      style: italic
    - asset: assets/font/Lato-Bold.ttf
      weight: 700
    - asset: assets/font/Lato-BoldItalic.ttf
      weight: 700
      style: italic

# This is the config for flutter_launcher_icons, which
# generates iOS and Android launcher icons from a source image.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/launcher_icon.png"
